default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: myblog_dev

test:
  <<: *default
  database: myblog_test

production:
  <<: *default
  database: myblog_production
